### ISSUE TITLE
Question regarding the Paper found in biorxiv.

### ISSUE THREAD

**Issue by CreatorZZY** [OluwadareLab/HiC-GNN#1]
Hello Dr.Van:
      I am a university student, being major in clinical medicine, from SZU in CN.
      Firstly, I appreciate your work, bringing such an amazing job to the world. HiC-GNN brings me to a new aspect to understand What GNN can do, and how to improve my work, in which I intend to use GCNN to solve a bioproblem. 
     Secondly, Some confuse met while Reading Paper:
     1. If redundancy nodes in the procedure--Binning Proceduing affects the Feature embedding(or representation) using LINE. (Or Ask Although the adjance node the be the node duplication. why redundancy nodes didn't not affect the embedding?)
     2. How to deal with the different result of redundancy nodes predicted by the model? Make average?
     3. Is 'Generalization' proceduing the work that minimize the ||oA-b||F and the target parameter is the Model? (Actually I didn't understand what T means.)

Thanks for your Time!!!

**Comment by vhovenga** [comment]
Hello and thank you for your questions. 

1. Redundancy nodes do not affect the embeddings. This is because the node embeddings are generated before the binning procedure. 
2. Redundancy nodes are only used in the alignment procedure. After the nodes are aligned, redundant nodes are discarded before predictions. Thus, there are no redundancies in the predictions. 
3. The  minimization of ||oA-b||F refers to the alignment of node embeddings prior to prediction. This step is necessary for generalization. This is because the distribution of the embeddings between two input maps may be different. T is the linear transformation that minimizes the distance between these two distributions. Say we trained a model using Ncol data and wish to make predictions on HindIII data. As mentioned, the embeddings for these two maps may be different. We calculate T (here A is the HindIII data and B is the Ncol data) to minimize this difference, we apply T to the HindIII data before sending it through our model so that the model is working with a similar distribution to the one with which it was trained. 

I hope that answers your questions.

**Comment by CreatorZZY** [comment]
Your answers solved my questions. Thanks for your time and the amazing work !
