### ISSUE TITLE
Illegal instruction error

### ISSUE THREAD

**Issue by beyzoskaya** [OluwadareLab/HiC-GNN#6]
Can I run the container in Macbook M2 chip, I got same error every time "Illegal instruction" even if I install Rosetta for the dependency mismatch of the image format and the machine.

**Comment by OluwadareLab** [comment]
We have not encountered this error before. Since it is a docker image, following the provided instructions we have been able to pull the image and run it on Linux PCs. We expect it to work on a Mac OS also. But it seems the issue you are facing might be a Docker or a machine compatibility issue which are unable to fully diagnose or help with.

**Comment by beyzoskaya** [comment]
Is it because of the version of the docker maybe? Can you please say the version of your Docker?

**Comment by OluwadareLab** [comment]
Our version is 24.0.2. That said, Docker images are designed to be compatible across multiple versions of Docker, which is one of the features that contribute to Docker's wide adoption in various environments, from development to production. This compatibility is maintained to ensure that Docker images built on one version can be run using newer or slightly older versions of the Docker engine without issues.  You can review Docker documentation. Though you are experiencing the issue, I cannot tell why that is the case.

**Comment by beyzoskaya** [comment]
Yes, I see but I couldn't find the problem before. It is because the Rosetta version of Docker in Mac. Among the permissions prepared for Docker, I should not have given permission to the amd64 version related to Rosetta.

**Comment by OluwadareLab** [comment]
Glad you were able to find the cause.
